linters:
  enable-all: true
  disable:
    - cyclop
    - depguard
    - dupl
    - err113
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - gocognit
    - gocyclo
    - godox
    - gofumpt
    - gomnd
    - govet
    - ireturn
    - mnd
    - nlreturn
    - paralleltest
    - perfsprint
    - recvcheck
    - tagalign
    - tagliatelle
    - testifylint
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    # disabled because they spew warnings re: generics
    - rowserrcheck
    - wastedassign
    # deprecated
    - execinquery
    - exportloopref

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true

  gci:
    sections:
      - standard # Standard section: captures all standard packages.
      - default # Default section: contains all imports that could not be matched to another section type.
      - prefix(github.com/twelvelabs/schemadoc) # Custom section: groups all imports with the specified Prefix.

  goconst:
    ignore-tests: true

  lll:
    line-length: 120

  revive:
    rules:
      - name: unused-parameter
        disabled: true

  staticcheck:
    checks:
      - "all"
      - "-SA5001"

severity:
  case-sensitive: false
  default-severity: error
