---
# Example config w/ defaults:
# - https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# MD013/line-length - Line length
MD013: false

# MD033/no-inline-html - Inline HTML
MD033: false
