---
name: build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  contents: read
  packages: write # if pushing docker images

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin@v4.1.1
        with:
          fetch-depth: 0
          # Need a PAT so that `make release-tag` will trigger the release workflow.
          # See: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          token: ${{ github.ref_name == 'main' && secrets.GH_PAT || secrets.GITHUB_TOKEN }}

      - name: Set up Homebrew
        uses: homebrew/actions/setup-homebrew@9e809e528c6aae1b87ed30f5d81fe75d0bfc6f38 # pin@master

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # pin@v5.0.0
        with:
          go-version-file: go.mod

      - name: Install dependencies
        run: make setup

      - name: Build
        run: make build

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Coverage
        uses: codecov/codecov-action@0cfda1dd0a4ad9efc75517f399d859cd1ea4ced1 # pin@v4.0.2

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4 # pin@v6.1.0
        if: github.ref_name == 'main'
        with:
          gpg_private_key: ${{ secrets.GH_COMMIT_SIGNING_KEY }}
          passphrase: ${{ secrets.GH_COMMIT_SIGNING_PASS }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Create release tag
        # Change to support different release channels
        # Versions from a non-main branch will look like: `v.0.0.0-branch-name`.
        if: github.ref_name == 'main'
        run: make release-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
